/*
 * YARA-Forge YARA Rule Package
 * https://github.com/YARAHQ/yara-forge
 * 
 * Rule Package Information
 * Name: core 
 * Description: Default YARA Rule Package - Core
 * YARA-Forge Version: 0.9.1
 * YARA-QA Commit: 7f1c7f4ad5b5164aa49361bf2a772795202d7e36
 * Minimum Quality: 70
 * Force Include Importance Level: 80
 * Force Exclude Importance Level: 50
 * Minimum Age (in days): 1
 * Minimum Score: 65
 * Creation Date: 2026-05-03
 * Number of Rules: 4960
 * Skipped: 3066 (age), 894 (quality), 961 (score), 2039 (importance)
 */

import "dotnet"
import "hash"
import "pe"


/*
 * YARA Rule Set
 * Repository Name: R3c0nst
 * Repository: https://github.com/fboldewin/YARA-rules/
 * Retrieval Date: 2026-05-03
 * Git Commit: 54e9e6899b258b72074b2b4db6909257683240c2
 * Number of Rules: 19
 * Skipped: 5 (age), 2 (quality), 0 (score), 0 (importance)
 *
 * 
 * LICENSE
 * 
 * NO LICENSE SET
 */

rule MALPEDIA_Win_Coinminer_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "dd71a564-9751-5c18-a6bf-b9b0587239f2"
		date = "2026-01-05"
		modified = "2026-01-06"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.coinminer"
		source_url = "https://github.com/malpedia/signator-rules//blob/173f2e2012643b57ff6521a58ba6dd57331de3c6/rules/win.coinminer_auto.yar#L1-L121"
		license_url = "N/A"
		logic_hash = "c6e378240c8214f1ad0ec61fc8d57006e837b16f1716923b20f2ac30be5b248c"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20260105"
		malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
		malpedia_version = "20251219"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8b8d24e5ffff 8b0485a05f9a00 f644010440 7409 803a1a 7504 33c0 }
		$sequence_1 = { 8b85f0feffff 85c0 7509 33d2 }
		$sequence_2 = { 83c801 85c0 741d 8d85d4fdffff }
		$sequence_3 = { ebcc 5f 5e 33c0 5b 8be5 }
		$sequence_4 = { c7465c60fd8f00 83660800 33ff 47 897e14 }
		$sequence_5 = { ff15???????? 6683bc24b002000000 8d8c24b0020000 ba???????? }
		$sequence_6 = { 7e58 bc80304a3e 60 4c 1c00 59 6443 }
		$sequence_7 = { 57 6868060000 0f57c0 894c2440 8d8424ec000000 c744242400004000 }
		$sequence_8 = { c3 8b04c50c509000 5d c3 55 8bec 8b4508 }
		$sequence_9 = { 8304240d cb 8d85b0fdffff 8945fc 85c0 745d 8b4df0 }

	condition:
		7 of them and filesize < 1523712
}

rule MALPEDIA_Win_Underminer_Ek_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "25419d82-2049-52ba-8173-e803bede2897"
		date = "2026-01-05"
		modified = "2026-01-06"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.underminer_ek"
		source_url = "https://github.com/malpedia/signator-rules//blob/173f2e2012643b57ff6521a58ba6dd57331de3c6/rules/win.underminer_ek_auto.yar#L1-L168"
		license_url = "N/A"
		logic_hash = "cef777a253424ada6724fda25a7a7fc2a7d290e0894ee3bdc7ea6fd0d09bd9ea"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20260105"
		malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
		malpedia_version = "20251219"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 56 e8???????? 83c404 53 e8???????? 83c404 8b551c }
		$sequence_1 = { 25ffff0000 3d4ee640bb 7404 3bc1 7501 }
		$sequence_2 = { 83c40c 66394e06 894d10 7630 83c710 8b07 }
		$sequence_3 = { 03c3 8901 eb18 3daafc0d7c }
		$sequence_4 = { 7463 8b55f4 8b0495582c4300 f644382848 }
		$sequence_5 = { 8ad0 8adc 88550f 807e0700 7417 0fb6813051fa7e 8a4dff }
		$sequence_6 = { 6a06 53 ff7508 53 ff55f0 85c0 7c07 }
		$sequence_7 = { 0f8535010000 83bd88feffff00 0f85a4040000 807d9a01 }
		$sequence_8 = { 885c012e 8b0495582c4300 804c012d04 46 }
		$sequence_9 = { c745f800000000 0f8444040000 837d3000 0f843a040000 }
		$sequence_10 = { 0f8776050000 52 51 e8???????? 83c408 c745c000000000 }
		$sequence_11 = { c745fc20000000 eb21 8bd0 83e220 }
		$sequence_12 = { 3e58 3e7f3e 98 3e4a }
		$sequence_13 = { 47 8d5101 0f1f8000000000 8a01 41 84c0 }
		$sequence_14 = { 66895dc0 ff7508 895dec ab ff760c 895df8 ab }
		$sequence_15 = { e8???????? 83c410 eb03 8d041a 5b 5d c3 }

	condition:
		7 of them and filesize < 466944
}

rule MALPEDIA_Win_Kingminer_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "dc87ee85-ad64-51c7-a30a-c6bd4d73fed8"
		date = "2026-01-05"
		modified = "2026-01-06"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.kingminer"
		source_url = "https://github.com/malpedia/signator-rules//blob/173f2e2012643b57ff6521a58ba6dd57331de3c6/rules/win.kingminer_auto.yar#L1-L114"
		license_url = "N/A"
		logic_hash = "a5745ddfac302b5a6ad793ecca6fc94da98fb5fc6ae2a187ff80bbe4b8e2d2c1"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20260105"
		malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
		malpedia_version = "20251219"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 8945f0 c745f400000000 3b0d???????? 0f8d8e010000 68???????? ff15???????? }
		$sequence_1 = { 8b8db0feffff e8???????? 8b95d8feffff 8b8db0feffff 52 8bf0 e8???????? }
		$sequence_2 = { 53 8b5f38 f6c301 7570 0fb74706 }
		$sequence_3 = { 0fb75714 8d4c3a24 85c0 7429 8bf0 }
		$sequence_4 = { 52 e9???????? a1???????? 6800040000 }
		$sequence_5 = { 3bf0 741e 68c1000000 ff15???????? 5b }
		$sequence_6 = { 68???????? ff15???????? 8b7508 c7465c88d00010 }
		$sequence_7 = { 8b0d???????? 8945ec 8b4624 83c628 }
		$sequence_8 = { 8975e4 33c0 39b8a0f70010 0f8491000000 }
		$sequence_9 = { 8b95d0feffff 2b4234 7419 83b9a000000000 7466 50 }

	condition:
		7 of them and filesize < 165888
}

rule MALPEDIA_Win_Waterminer_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "8c2bad66-5d35-57b7-b9da-21c6dec00989"
		date = "2026-01-05"
		modified = "2026-01-06"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.waterminer"
		source_url = "https://github.com/malpedia/signator-rules//blob/173f2e2012643b57ff6521a58ba6dd57331de3c6/rules/win.waterminer_auto.yar#L1-L162"
		license_url = "N/A"
		logic_hash = "f10b4bcaeeaace43d5cd2141c609b5656e22416293022c0fdf8f9cf3861e271d"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20260105"
		malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
		malpedia_version = "20251219"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 51 6804100020 8b5508 52 }
		$sequence_1 = { 8b9584fdffff 0fb68208794400 ff2485f0784400 8b8decfdffff 83c904 898decfdffff }
		$sequence_2 = { 03bc24a8000000 488bcd 4c8d0d35cb0300 83e13f }
		$sequence_3 = { b804000000 6bc014 8b8880434b00 330d???????? 894dfc }
		$sequence_4 = { 02d0 49ffc3 418d4001 881418 }
		$sequence_5 = { 8d8518f5ffff 50 e8???????? 83c404 898500f7ffff e8???????? 85c0 }
		$sequence_6 = { 0344240c 4403d0 428b4405e7 418bd2 }
		$sequence_7 = { 03442410 4403e8 428b4405e7 418bd5 }
		$sequence_8 = { 03c1 03d0 488d051e580500 418b0400 }
		$sequence_9 = { 6bc903 898180434b00 68???????? 8b55fc 52 }
		$sequence_10 = { 02c8 41880c18 418a03 240f }
		$sequence_11 = { 8945d8 837dd806 0f8797000000 8b4dd8 ff248d54e94600 8b55f8 }
		$sequence_12 = { 83fa78 7f19 0fbe85f3fdffff 0fbe8800ec4900 83e10f 898d28fdffff eb0a }
		$sequence_13 = { 8945f0 817df005010000 7302 eb05 e8???????? 8b4df0 c681f82c4b0000 }
		$sequence_14 = { 03c0 2bc8 0f84ec040000 8d41ff 8b848288d20600 }
		$sequence_15 = { 0344240c 4403d0 488d051a560500 418b0400 }

	condition:
		7 of them and filesize < 1556480
}

rule MALPEDIA_Win_Cerbu_Miner_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "77652d6a-745f-5552-8901-83bf555706f4"
		date = "2023-12-06"
		modified = "2023-12-08"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.cerbu_miner"
		source_url = "https://github.com/malpedia/signator-rules//blob/173f2e2012643b57ff6521a58ba6dd57331de3c6/rules/win.cerbu_miner_auto.yar#L1-L134"
		license_url = "N/A"
		logic_hash = "e4927a587588bc11053fcbade5bb9500364c9a656d383eb318cc8486464f3cce"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20231130"
		malpedia_hash = "fc8a0e9f343f6d6ded9e7df1a64dac0cc68d7351"
		malpedia_version = "20230808"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { 88b42480000000 eb3f 83e902 7433 83e904 7413 83e909 }
		$sequence_1 = { 7412 48 8d0d0b360500 48 83c428 48 ff25???????? }
		$sequence_2 = { 8d4601 c643012e 48 63c8 41 8d4602 48 }
		$sequence_3 = { 85d2 7427 85c9 b800040000 41 b800080000 44 }
		$sequence_4 = { f6473801 7402 eb18 48 8bcf ff15???????? f6473801 }
		$sequence_5 = { e9???????? 45 8bfd 44 89ad50010000 e9???????? 44 }
		$sequence_6 = { 48 89442420 e8???????? 48 8bd7 48 8bcb }
		$sequence_7 = { 89b42418010000 8b74242c 83feff 7515 837f0c00 7c0f 48 }
		$sequence_8 = { 8d057b52f9ff 48 894518 c745b0e6070000 48 c745c000000200 48 }
		$sequence_9 = { 44 2bc0 44 8903 33c0 48 8b5c2438 }

	condition:
		7 of them and filesize < 1040384
}

rule MALPEDIA_Win_Monero_Miner_Auto : FILE
{
	meta:
		description = "autogenerated rule brought to you by yara-signator"
		author = "Felix Bilstein - yara-signator at cocacoding dot com"
		id = "53964e17-4946-5df0-a485-9eaee6f615c2"
		date = "2026-01-05"
		modified = "2026-01-06"
		reference = "https://malpedia.caad.fkie.fraunhofer.de/details/win.monero_miner"
		source_url = "https://github.com/malpedia/signator-rules//blob/173f2e2012643b57ff6521a58ba6dd57331de3c6/rules/win.monero_miner_auto.yar#L1-L133"
		license_url = "N/A"
		logic_hash = "cffe54ca1957e07a44d930d7017ae2111987cffb75cbed1acab293924f2ab98e"
		score = 75
		quality = 75
		tags = "FILE"
		version = "1"
		tool = "yara-signator v0.6.0"
		signator_config = "callsandjumps;datarefs;binvalue"
		malpedia_rule_date = "20260105"
		malpedia_hash = "19b79e7cab4eaf532122e5b45a77dd8f6bb5cc79"
		malpedia_version = "20251219"
		malpedia_license = "CC BY-SA 4.0"
		malpedia_sharing = "TLP:WHITE"

	strings:
		$sequence_0 = { c6043000 c744240811000000 89442404 c70424???????? e8???????? 85c0 7411 }
		$sequence_1 = { e8???????? 0fb643fa 8d4e04 c7442404???????? 890c24 89442408 e8???????? }
		$sequence_2 = { 8b6c240c 136c2424 8b8c24d4000000 8bbc24dc000000 89c2 8b4350 31f2 }
		$sequence_3 = { e8???????? 8d9424a0000000 8d442460 b901000000 e8???????? 8d542460 8d8424a0000000 }
		$sequence_4 = { 890424 e8???????? 83f8ff 0f8463050000 817c2434ff3f0000 8b442430 0f96c2 }
		$sequence_5 = { 8b94247c010000 898c2448020000 899c244c020000 8b9c248c010000 89c5 0fa4d017 0fa4ea17 }
		$sequence_6 = { 8db4248c000000 c60000 89442414 8b8398000000 8974240c c7442404???????? 89442410 }
		$sequence_7 = { 8b542428 8354242c00 83c340 836c242040 c1e206 39542414 0f87c3feffff }
		$sequence_8 = { ffd6 83f8ff 75de 81c4cc0f0000 89e8 5b 5e }
		$sequence_9 = { 8906 8b7413fc 897411fc 8b7d14 89de 81c784000000 }

	condition:
		7 of them and filesize < 1425408
}

rule DITEKSHEN_MALWARE_Win_Coinminer01 : FILE
{
	meta:
		description = "Detects coinmining malware"
		author = "ditekSHen"
		id = "739e7cea-c6b6-5add-86d4-382b00e2b645"
		date = "2020-11-06"
		modified = "2024-11-01"
		reference = "https://github.com/ditekshen/detection"
		source_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/yara/malware.yar#L5778-L5790"
		license_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/LICENSE.txt"
		logic_hash = "31a7531ecc7b8a35ba882c17d15bd3581e65b4b99dd3a7cb8bca8f6edf204114"
		score = 75
		quality = 75
		tags = "FILE"

	strings:
		$s1 = "-o pool." ascii wide
		$s2 = "--cpu-max-threads-hint" ascii wide
		$s3 = "-P stratum" ascii wide
		$s4 = "--farm-retries" ascii wide
		$dl = "github.com/ethereum-mining/ethminer/releases/download" ascii wide

	condition:
		uint16( 0 ) == 0x5a4d and ( 3 of ( $s* ) or ( $dl ) )
}

rule DITEKSHEN_MALWARE_Win_Coinminer02 : FILE
{
	meta:
		description = "Detects coinmining malware"
		author = "ditekSHen"
		id = "1878a1b5-4e97-5575-802e-573caded2b3a"
		date = "2020-11-06"
		modified = "2024-11-01"
		reference = "https://github.com/ditekshen/detection"
		source_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/yara/malware.yar#L6553-L6571"
		license_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/LICENSE.txt"
		logic_hash = "83760aef667819923a2ac67c006e03bb6d4260b7a4aedd691dd5b145fb50d5c1"
		score = 75
		quality = 75
		tags = "FILE"

	strings:
		$s1 = "%s/%s (Windows NT %lu.%lu" fullword ascii
		$s2 = "\\Microsoft\\Libs\\WR64.sys" wide
		$s3 = "\\\\.\\WinRing0_" wide
		$s4 = "pool_wallet" ascii
		$s5 = "cryptonight" ascii
		$s6 = "mining.submit" ascii
		$c1 = "stratum+ssl://" ascii
		$c2 = "daemon+http://" ascii
		$c3 = "stratum+tcp://" ascii
		$c4 = "socks5://" ascii
		$c5 = "losedaemon+https://" ascii

	condition:
		uint16( 0 ) == 0x5a4d and ( 3 of ( $s* ) and 1 of ( $c* ) )
}

rule DITEKSHEN_MALWARE_Win_Coinminer03 : FILE
{
	meta:
		description = "Detects coinmining malware"
		author = "ditekSHen"
		id = "e0e57557-7c46-5336-b904-c4c1f142bd81"
		date = "2020-11-06"
		modified = "2024-11-01"
		reference = "https://github.com/ditekshen/detection"
		source_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/yara/malware.yar#L7506-L7528"
		license_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/LICENSE.txt"
		logic_hash = "f22e1af955a0d132dda820fe5e5e1ae2f077b7264ce1f0125a2f37c0da6b6508"
		score = 75
		quality = 75
		tags = "FILE"

	strings:
		$s1 = "UnVzc2lhbiBTdGFuZGFyZCBUaW1l" wide
		$s2 = "/xmrig" wide
		$s3 = "/gminer" wide
		$s4 = "-o {0} -u {1} -p {2} -k --cpu-priority 0 --threads={3}" wide
		$s5 = "--algo ethash --server" wide
		$s6 = "--algo kawpow --server" wide
		$cnc1 = "/delonl.php?hwid=" fullword wide
		$cnc2 = "/gateonl.php?hwid=" fullword wide
		$cnc3 = "&cpuname=" fullword wide
		$cnc4 = "&gpuname=" fullword wide
		$cnc5 = "{0}/gate.php?hwid={1}&os={2}&cpu={3}&gpu={4}&dateinstall={5}&gpumem={6}" fullword wide
		$cnc6 = "/del.php?hwid=" fullword wide
		$f1 = "<StartGpuethGminer>b__" ascii
		$f2 = "<StartGpuetcGminer>b__" ascii
		$f3 = "<StartGpurvnGminer>b__" ascii

	condition:
		uint16( 0 ) == 0x5a4d and ( 3 of ( $cnc* ) or ( 2 of ( $f* ) and ( 1 of ( $s* ) or 1 of ( $f* ) ) ) or all of ( $f* ) or 5 of ( $s* ) )
}

rule DITEKSHEN_MALWARE_Win_Coinminer04 : FILE
{
	meta:
		description = "Detects coinmining malware"
		author = "ditekSHen"
		id = "d90d8ad3-20b7-5bb4-8c58-3488c60ed9a2"
		date = "2020-11-06"
		modified = "2024-11-01"
		reference = "https://github.com/ditekshen/detection"
		source_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/yara/malware.yar#L7838-L7858"
		license_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/LICENSE.txt"
		logic_hash = "2ef60dbf0bac3d5910635bb011a45e5ebc1392094b10425604fa9dd290198f8b"
		score = 75
		quality = 75
		tags = "FILE"

	strings:
		$s1 = "createDll" fullword ascii
		$s2 = "getTasks" fullword ascii
		$s3 = "SetStartup" fullword ascii
		$s4 = "loadUrl" fullword ascii
		$s5 = "Processer" fullword ascii
		$s6 = "checkProcess" fullword ascii
		$s7 = "runProcess" fullword ascii
		$s8 = "createDir" fullword ascii
		$cnc1 = "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0" fullword wide
		$cnc2 = "?hwid=" fullword wide
		$cnc3 = "?timeout=1" fullword wide
		$cnc4 = "&completed=" fullword wide
		$cnc5 = "/cmd.php" wide

	condition:
		uint16( 0 ) == 0x5a4d and ( 5 of ( $s* ) and 1 of ( $cnc* ) )
}

rule DITEKSHEN_MALWARE_Win_Nplusminer
{
	meta:
		description = "Detects PowerShell based NPlusMiner"
		author = "ditekSHen"
		id = "a16b504f-e69a-5abb-8e37-01bf7c2df6ef"
		date = "2020-11-06"
		modified = "2024-11-01"
		reference = "https://github.com/ditekshen/detection"
		source_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/yara/malware.yar#L9051-L9064"
		license_url = "https://github.com/ditekshen/detection/blob/e76c93dcdedff04076380ffc60ea54e45b313635/LICENSE.txt"
		logic_hash = "f6b81c2276765455d46e20ed81e19caa3ae36a31827568486a09bc1619ec478c"
		score = 75
		quality = 75
		tags = ""
		snort_sid = "920284"

	strings:
		$s1 = "$Core | Add-Member @{IsReadOnly = $((Get-ItemProperty -Path \".\\Includes\\Core.ps1\").IsReadOnly)} -Force" fullword ascii
		$s2 = "$Core | Add-Member @{MinerCustomConfig = $((Get-Content \".\\Config\\MinerCustomConfig.json\" -Raw))} -Force" fullword ascii
		$s3 = "If ($Variables.CheatGuy -and $Core.corehash -in $Hashes -and $Core.ScriptStartDate -le (Get-Date)" ascii
		$s4 = "Try{(Get-ItemProperty -Path \".\\Includes\\Core.ps1\").IsReadOnly = $false} catch {}" fullword ascii
		$s5 = " NPlusMiner/" ascii

	condition:
		3 of them
}

rule SEKOIA_Miner_Win_Xmrig_Strings : FILE
{
	meta:
		description = "Detects XMRig EXE"
		author = "Sekoia.io"
		id = "35f203aa-20cd-4235-9ead-b34be14255d5"
		date = "2024-01-04"
		modified = "2024-12-19"
		reference = "https://github.com/SEKOIA-IO/Community"
		source_url = "https://github.com/SEKOIA-IO/Community/blob/4a791f6fe20b053bc2acd963bb9955f6cd385791/yara_rules/miner_win_xmrig_strings.yar#L1-L35"
		license_url = "https://github.com/SEKOIA-IO/Community/blob/4a791f6fe20b053bc2acd963bb9955f6cd385791/LICENSE.md"
		logic_hash = "34aa0da9d3bb277927c87a3745ec9e35881682319c91141da6ff1cff7e0610d9"
		score = 75
		quality = 80
		tags = "FILE"
		version = "1.0"
		classification = "TLP:CLEAR"

	strings:
		$ = "XMRig "
		$ = "pool_wallet"
		$ = "IP Address currently banned"
		$ = "rigid"
		$ = "diff_current"
		$ = "shares_good"
		$ = "shares_total"
		$ = "avg_time"
		$ = "avg_time_ms"
		$ = "hashes_total"
		$ = "pool address"
		$ = "ping time"
		$ = "connection time"
		$ = "daemon+wss://"
		$ = "daemon+https://"
		$ = "daemon+http://"
		$ = "socks5://"
		$ = "stratum+ssl://"
		$ = "stratum+tcp://"

	condition:
		uint32be( 0 ) == 0x5A4D and filesize < 15MB and 7 of them
}

rule SEKOIA_Miner_Lin_Xmrig_Strings : FILE
{
	meta:
		description = "Detects XMRig ELF"
		author = "Sekoia.io"
		id = "2f99020b-424c-4433-860c-5e9ab4e1f1de"
		date = "2022-09-08"
		modified = "2024-12-19"
		reference = "https://github.com/SEKOIA-IO/Community"
		source_url = "https://github.com/SEKOIA-IO/Community/blob/4a791f6fe20b053bc2acd963bb9955f6cd385791/yara_rules/miner_lin_xmrig_strings.yar#L1-L36"
		license_url = "https://github.com/SEKOIA-IO/Community/blob/4a791f6fe20b053bc2acd963bb9955f6cd385791/LICENSE.md"
		logic_hash = "4946e5099d7d342c8cf6644146ffec8506e786a1d4de0b05ef039bcf2b0fdad2"
		score = 75
		quality = 80
		tags = "FILE"
		version = "1.0"
		modification_date = "2024-01-04"
		classification = "TLP:CLEAR"

	strings:
		$ = "XMRig "
		$ = "pool_wallet"
		$ = "IP Address currently banned"
		$ = "rigid"
		$ = "diff_current"
		$ = "shares_good"
		$ = "shares_total"
		$ = "avg_time"
		$ = "avg_time_ms"
		$ = "hashes_total"
		$ = "pool address"
		$ = "ping time"
		$ = "connection time"
		$ = "daemon+wss://"
		$ = "daemon+https://"
		$ = "daemon+http://"
		$ = "socks5://"
		$ = "stratum+ssl://"
		$ = "stratum+tcp://"

	condition:
		uint32be( 0 ) == 0x7f454c46 and filesize < 10MB and 7 of them
}

rule SIGNATURE_BASE_HKTL_NET_GUID_Minerdropper : FILE
{
	meta:
		description = "Detects c# red/black-team tools via typelibguid"
		author = "Arnim Rupp (https://github.com/ruppde)"
		id = "607f72df-b0c1-53df-bf2c-592f55cbfcb7"
		date = "2020-12-13"
		modified = "2025-08-15"
		reference = "https://github.com/DylanAlloy/MinerDropper"
		source_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/yara/gen_github_net_redteam_tools_guids.yar#L2194-L2208"
		license_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/LICENSE"
		logic_hash = "1a604745a0d95c54be0d1b183486aad0751aee825574500fbff6380571565a18"
		score = 75
		quality = 85
		tags = "FILE"
		license = "Detection Rule License 1.1 https://github.com/Neo23x0/signature-base/blob/master/LICENSE"

	strings:
		$typelibguid0lo = "46a7af83-1da7-40b2-9d86-6fd6223f6791" ascii wide
		$typelibguid1lo = "8433a693-f39d-451b-955b-31c3e7fa6825" ascii wide

	condition:
		( uint16( 0 ) == 0x5A4D and uint32( uint32( 0x3C ) ) == 0x00004550 ) and any of them
}

rule SIGNATURE_BASE_HKTL_NET_GUID_Lime_Miner : FILE
{
	meta:
		description = "Detects VB.NET red/black-team tools via typelibguid"
		author = "Arnim Rupp (https://github.com/ruppde)"
		id = "d0631817-10a2-55bf-a41d-226fa0dcb9f9"
		date = "2020-12-30"
		modified = "2025-08-15"
		reference = "https://github.com/NYAN-x-CAT/Lime-Miner"
		source_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/yara/gen_github_net_redteam_tools_guids.yar#L3898-L3911"
		license_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/LICENSE"
		logic_hash = "4b7f810efd907477736f40b9537d1ad99896e28c89bd571244256c385c387bfa"
		score = 75
		quality = 85
		tags = "FILE"
		license = "Detection Rule License 1.1 https://github.com/Neo23x0/signature-base/blob/master/LICENSE"

	strings:
		$typelibguid0lo = "13958fb9-dfc1-4e2c-8a8d-a5e68abdbc66" ascii wide

	condition:
		( uint16( 0 ) == 0x5A4D and uint32( uint32( 0x3C ) ) == 0x00004550 ) and any of them
}

rule SIGNATURE_BASE_Crime_H2Miner_Kinsing : FILE
{
	meta:
		description = "Rule to find Kinsing malware"
		author = "Tony Lambert, Red Canary"
		id = "1cabca0d-7134-517e-b82e-f2b20b4d1c34"
		date = "2020-06-09"
		modified = "2023-12-05"
		reference = "https://github.com/Neo23x0/signature-base"
		source_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/yara/crime_h2miner_kinsing.yar#L1-L20"
		license_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/LICENSE"
		logic_hash = "8795f01f4ce85ca37a4e4667a4ee9756dae6af42884cf79830877a5c35a3bd3b"
		score = 75
		quality = 85
		tags = "FILE"

	strings:
		$s1 = "-iL $INPUT --rate $RATE -p$PORT -oL $OUTPUT"
		$s2 = "libpcap"
		$s3 = "main.backconnect"
		$s4 = "main.masscan"
		$s5 = "main.checkHealth"
		$s6 = "main.redisBrute"
		$s7 = "ActiveC2CUrl"
		$s8 = "main.RC4"
		$s9 = "main.runTask"

	condition:
		( uint32( 0 ) == 0x464C457F ) and filesize > 1MB and all of them
}


rule SIGNATURE_BASE_SUSP_LNX_SH_Cryptominer_Indicators_Dec20_1 : FILE
{
	meta:
		description = "Detects helper script used in a crypto miner campaign"
		author = "Florian Roth (Nextron Systems)"
		id = "e376e0e1-1490-5ad4-8ca2-d28ca1c0b51a"
		date = "2020-12-31"
		modified = "2023-12-05"
		reference = "https://www.intezer.com/blog/research/new-golang-worm-drops-xmrig-miner-on-servers/"
		source_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/yara/crime_crypto_miner.yar#L2-L17"
		license_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/LICENSE"
		logic_hash = "4acd1b77307dbf23f95f7a2024209bee714c6931182aff16455ea6b7e4a6f287"
		score = 65
		quality = 85
		tags = "FILE"
		hash1 = "3298dbd985c341d57e3219e80839ec5028585d0b0a737c994363443f4439d7a5"

	strings:
		$x1 = "miner running" fullword ascii
		$x2 = "miner runing" fullword ascii
		$x3 = " --donate-level 1 "
		$x4 = " -o pool.minexmr.com:5555 " ascii

	condition:
		filesize < 20KB and 1 of them
}

rule SIGNATURE_BASE_PUA_WIN_XMRIG_Cryptocoin_Miner_Dec20 : FILE
{
	meta:
		description = "Detects XMRIG crypto coin miners"
		author = "Florian Roth (Nextron Systems)"
		id = "4dfb04e9-fbba-5a6f-ad20-d805025d2d74"
		date = "2020-12-31"
		modified = "2023-12-05"
		reference = "https://www.intezer.com/blog/research/new-golang-worm-drops-xmrig-miner-on-servers/"
		source_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/yara/crime_crypto_miner.yar#L19-L33"
		license_url = "https://github.com/Neo23x0/signature-base/blob/682f9b011abd6af6c2adf3270d4bfad7d28bb21f/LICENSE"
		logic_hash = "c39aee669a98bcc9d07821aef248096e45a6c54ab22b8b98c0a393b445f3934e"
		score = 75
		quality = 85
		tags = "FILE"
		hash1 = "b6154d25b3aa3098f2cee790f5de5a727fc3549865a7aa2196579fe39a86de09"

	strings:
		$x1 = "xmrig.exe" fullword wide
		$x2 = "xmrig.com" fullword wide
		$x3 = "* for x86, CRYPTOGAMS" fullword ascii

	condition:
		uint16( 0 ) == 0x5a4d and filesize < 6000KB and 2 of them or all of them
}